import { lazy } from 'react';

export const CATALOG_DETAIL_LOADERS = {
  'fonaments/universalcard': lazy(() => import('./detalls/EspecimenUniversalCard.jsx')),
  'inventari/global': lazy(() => import('./detalls/EspecimenInventariGlobal.jsx')),
  'estructura/shell': lazy(() => import('./detalls/EspecimenShell.jsx')),
  'estructura/page': lazy(() => import('./detalls/EspecimenPage.jsx')),
  'estructura/gestor': lazy(() => import('./detalls/EspecimenGestor.jsx')),
  'estructura/divisor': lazy(() => import('./detalls/EspecimenDivisor.jsx')),
  'formularis/boto': lazy(() => import('./detalls/EspecimenBoto.jsx')),
  'formularis/camp': lazy(() => import('./detalls/EspecimenCamp.jsx')),
  'formularis/opcions': lazy(() => import('./detalls/EspecimenOpcions.jsx')),
  'formularis/pindola': lazy(() => import('./detalls/EspecimenPindola.jsx')),
  'formularis/cerca': lazy(() => import('./detalls/EspecimenCerca.jsx')),
  'formularis/formulari-complex': lazy(() => import('./detalls/EspecimenFormulariComplex.jsx')),
  'navegacio/pestanyes': lazy(() => import('./detalls/EspecimenPestanyes.jsx')),
  'navegacio/molla': lazy(() => import('./detalls/EspecimenMolla.jsx')),
  'navegacio/paginacio': lazy(() => import('./detalls/EspecimenPaginacio.jsx')),
  'navegacio/acordio': lazy(() => import('./detalls/EspecimenAcordio.jsx')),
  'navegacio/nav-mobil': lazy(() => import('./detalls/EspecimenNavMobil.jsx')),
  'retroalimentacio/alerta': lazy(() => import('./detalls/EspecimenAlerta.jsx')),
  'retroalimentacio/insignia': lazy(() => import('./detalls/EspecimenInsignia.jsx')),
  'retroalimentacio/buit': lazy(() => import('./detalls/EspecimenBuit.jsx')),
  'retroalimentacio/carrega': lazy(() => import('./detalls/EspecimenCarrega.jsx')),
  'retroalimentacio/progres': lazy(() => import('./detalls/EspecimenProgres.jsx')),
  'superposicions/dialeg': lazy(() => import('./detalls/EspecimenDialeg.jsx')),
  'superposicions/confirmacio': lazy(() => import('./detalls/EspecimenConfirmacio.jsx')),
  'superposicions/calaix': lazy(() => import('./detalls/EspecimenCalaix.jsx')),
  'superposicions/pista': lazy(() => import('./detalls/EspecimenPista.jsx')),
  'superposicions/menu': lazy(() => import('./detalls/EspecimenMenu.jsx')),
  'superposicions/toast': lazy(() => import('./detalls/EspecimenToast.jsx')),
};
