// Dades de mercat recuperades de la versió original.
export const MOCK_MARKET_ITEMS = [{
  id: 'mac-mini-m4',
  type: 'product',
  title: 'Mac Mini Apple M4, 24/512GB',
  subtitle: 'Com nou - Apple - Gris',
  description: 'Mac Mini en perfecte estat. Comprat al març de 2025.\n\n- Processador Apple M4.\n- 24GB de RAM.\n- 512 GB d\'emmagatzematge.\n\nCaracterístiques adicionals:\n- Color: Gris\n- Estat: Com nou\n- Marca: Apple',
  price: '900.00€',
  seller: 'Mestre Poble',
  avatar_url: '/assets/system/ui/logo-socdepoble-cuadrat-verd.svg',
  author_name: 'Mestre Poble',
  population: 'La Torre de les Maçanes',
  author_role: 'user',
  author_id: 'javillinares',
  official: false,
  pinned: false,
  variations: [],
  images: ['/assets/uploads/brain/mac_mini_m4_1787721966622.jpg'],
  category_slug: 'tecnologia',
  tag: 'ordinador',
  is_pinned: false,
  lat: 38.5919,
  lng: -0.4184,
  created_at: '2026-02-15T12:00:00.000Z'
}, {
  id: 'samarreta-socdepoble',
  type: 'product',
  title: 'Samarreta Sóc de Poble',
  subtitle: "L'edició definitiva amb el logotip complet",
  description: "Mapa del tresor sobre cotó resistent. La imatge complementa el text, no el substituïx.",
  price: '15.00€',
  seller: 'Sóc de Poble',
  avatar_url: '/assets/system/ui/logo-socdepoble-cuadrat-verd.svg',
  author_name: 'Sóc de Poble',
  population: 'La Torre de les Maçanes',
  author_role: 'business',
  author_id: 'soc-de-poble_official',
  author_entity_id: 'socdepoble',
  official: true,
  pinned: true,
  variations: [{
    name: 'Edició Gris Plom',
    price: '15.00€',
    description: 'Cotó Roly Gris. Discreta i elegant.',
    image: '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/02-samarreta-socdepoble-roly-plom-oscur-1024px.png'
  }, {
    name: 'Edició Verda',
    price: '15.00€',
    description: 'Edició especial en color verd pi.',
    image: '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/samarreta-socdepoble-verd-638px.jpg',
    stock_status: 'Esgotat'
  }],
  images: [
    '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/01-chica-jersey.png',
    '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/02-samarreta-socdepoble-roly-plom-oscur-1024px.png',
    '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/03-young-man-tshirt.png',
    '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/04-iaia-tshirt.png',
    '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/06-group-tshirt.png',
    '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/07-rustic-detail.png',
    '/assets/uploads/empresa/soc-de-poble/mercat/samarreta-soc-de-poble/08-mestre-obres-perfil-1024px.jpg'
  ],
  category_slug: 'roba',
  tag: 'samarreta',
  is_pinned: true,
  pinned_position: 1,
  lat: 38.5582,
  lng: -0.4413,
  created_at: '2026-08-15T12:33:00.000Z'
}];
